<?php
  if( !defined('APP_VERSION') ) exit('You can\'t access this file');

  $out = '';
  $out .= '<form id="regestration-form" name="regestration-form" class="regestration-form col-md-6" method="post" action="#">';
    $out .= '<h2>Sign Up</h2>';
    $out .= '<table>';
      $out .= '<tr>';
        $out .= '<td>';
          $out .= '<label for="user_name">Login: </label>';
        $out .= '</td>';
        $out .= '<td>';
          $out .= '<input type="text" id="user_name" name="user_name">';
        $out .= '</td>';
      $out .= '</tr>';
      $out .= '<tr>';
        $out .= '<td>';
          $out .= '<label for="user_email">Email: </label>';
        $out .= '</td>';
        $out .= '<td>';
          $out .= '<input type="email" id="user_email" name="user_email">';
        $out .= '</td>';
      $out .= '</tr>';
      $out .= '<tr>';
        $out .= '<td>';
          $out .= '<label for="user_first_name">First Name: </label>';
        $out .= '</td>';
        $out .= '<td>';
          $out .= '<input type="text" id="user_first_name" name="user_first_name">';
        $out .= '</td>';
      $out .= '</tr>';
      $out .= '<tr>';
        $out .= '<td>';
          $out .= '<label for="user_last_name">Last Name: </label>';
        $out .= '</td>';
        $out .= '<td>';
          $out .= '<input type="text" id="user_last_name" name="user_last_name">';
        $out .= '</td>';
      $out .= '</tr>';
      $out .= '<tr>';
        $out .= '<td>';
          $out .= '<label for="user_pass">Password: </label>';
        $out .= '</td>';
        $out .= '<td>';
          $out .= '<input type="password" id="user_pass" name="user_pass">';
        $out .= '</td>';
      $out .= '</tr>';
      $out .= '<tr>';
        $out .= '<td>';
        $out .= '</td>';
        $out .= '<td>';
          $out .= '<input type="submit" name="submit" value="Register">';
        $out .= '</td>';
      $out .= '</tr>';
    $out .= '</table>';
  $out .= '</form>';
  return $out;
?>